openapi: 3.0.0
info:
  title: Ventti-API
  description: Venttipelipalvelimen ohjelmointirajapinta.
  version: 0.0.1
paths:
  '/game':
    summary: 'Peli-instanssin tilan käsittelyyn liittyvät toiminnot. '
    description: Peli-instanssi sisältää pelin jakojen tulokset ja nykyisen jaon tilan.
    post:
      summary: Luo uusi peli
      description: Luo uuden tyhjän pelin ja palauttaa sen tunnisteen.
      operationId: ''
      responses:
        '201':
          description: Uusi peli luotu
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    
  '/game/:id':
    summary: Peli-instanssin tilan käsittely
    description: >-
      Peli-instanssin tilaa käsittelevät operaatiot palauttavat aina koko pelin
      tilan.
    get:
      summary: Hae pelin tila
      description: ''
      operationId: ''
      responses:
        '200':
          description: Toiminto onnistui.
        '404':
          description: Tuntematon peli-id
    post:
      summary: Pelin pelaamistoiminnot
      description: >-
        Pelitoiminnot annetaan action-attribuutissa. Onnistunut pelitoiminto
        palauttaa pelin uuden tilan.
      operationId: ''
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: Pelin tunniste
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/Action'
      responses:
        '200':
          description: Operation successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/State'
        '400':
          description: Tuntematon toiminto
        '404':
          description: Tuntematon peli-id

components:
  schemas:
    Action:
      type: object
      properties:
        action:
          type: string
          enum: 
            - 'deal'
            - 'hit'
            - 'stand'
            - 'play'

    Score:
      type: object
      properties:
        player: 
          type: integer
        dealer:
          type: integer
    
    Suit:
      type: object
      properties:
        name:
          type: string
        symbol:
          type: string
    
    Card:
      type: object
      properties:
        suit:
          $ref: '#/components/schemas/Suit'
        value:
          type: integer
        label:
          type: string
    
    Hand:
      type: object
      properties:
        cards:
          type: array
          items:
            $ref: '#/components/schemas/Card'
    
    Active:
      type: string
      enum: 
        - 'null'
        - player
        - dealer
  
    Resolve:
      type: object
      properties:
        winner:
          type: string
        message:
          type: string
  
    State:
      type: object
      properties:
        score: 
          $ref: '#/components/schemas/Score'
        dealer:
          $ref: '#/components/schemas/Hand'
        player:
          $ref: '#/components/schemas/Hand'
        active:
          $ref: '#/components/schemas/Active'
        resolve:
          $ref: '#/components/schemas/Resolve'
